services:
  web:
    build: .
    environment:
      - SQLITE_DB_PATH=$SQLITE_DB_PATH
      - JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
      - ORIGIN=http://localhost:3000
    ports:
      - 3000:3000
    volumes:
      - ./db:/app/db
